#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

SOURCE_ROOT="$(kokoro_source_root "$SCRIPT_DIR")"
SOURCE_COMMANDS_DIR="$(kokoro_source_commands_dir "$SOURCE_ROOT")"
SOURCE_KNOWLEDGE_DIR="$(kokoro_source_knowledge_dir "$SOURCE_ROOT")"
SOURCE_MANIFEST="$(kokoro_source_manifest "$SOURCE_ROOT")"
CLAUDE_HOME="$(kokoro_claude_home)"
PACKAGE_HOME="$(kokoro_package_home "$CLAUDE_HOME")"
COMMANDS_TARGET="$CLAUDE_HOME/commands"
CODEX_HOME_PATH="$(kokoro_codex_home)"
CODEX_SKILL_DIR="$CODEX_HOME_PATH/skills/kokoro"
CONFIG_HOME="$(kokoro_config_home)"
META_ADS_ENV_FILE="$(kokoro_meta_ads_env_file "$CONFIG_HOME")"
PACKAGE_DISPLAY="$(kokoro_display_path "$PACKAGE_HOME")"

require_file() {
    local file="$1"
    if [ ! -f "$file" ]; then
        echo "Kokoro setup error: missing required file: $file" >&2
        exit 2
    fi
}

write_wrapper() {
    local source_file="$1"
    local command_name
    local wrapper_file

    command_name="$(basename "$source_file")"
    wrapper_file="$COMMANDS_TARGET/$command_name"

    cat > "$wrapper_file" <<EOF
---
kokoro_owned: true
kokoro_source: "commands/$command_name"
kokoro_package_home: "$PACKAGE_DISPLAY"
---

<!-- Generated by Kokoro installer. Do not edit directly. -->

# /${command_name%.md}

Before executing this command:

1. Expand \`$PACKAGE_DISPLAY\` as the Kokoro package root.
2. Read \`$PACKAGE_DISPLAY/IDENTITY_kokoro.md\`.
3. Read the source command: \`$PACKAGE_DISPLAY/commands/$command_name\`.
4. Resolve bare Kokoro knowledge references under \`$PACKAGE_DISPLAY/knowledge/\`,
   \`$PACKAGE_DISPLAY/knowledge/google-ads/\`, or \`$PACKAGE_DISPLAY/knowledge/lux/\`.
5. If identity, command source, or required knowledge is missing, stop and tell
   the user to run Kokoro verify/update.
6. Never assume the current working directory is the Kokoro package.
EOF
}

remove_existing_wrappers() {
    if [ ! -d "$COMMANDS_TARGET" ]; then
        return
    fi

    while IFS= read -r wrapper_file; do
        if grep -q '^kokoro_owned: true$' "$wrapper_file"; then
            rm -f "$wrapper_file"
        fi
    done < <(find "$COMMANDS_TARGET" -maxdepth 1 -type f -name 'kokoro*.md' | sort)
}

write_codex_skill() {
    mkdir -p "$CODEX_SKILL_DIR"

    cat > "$CODEX_SKILL_DIR/SKILL.md" <<EOF
---
name: kokoro
description: Route Kokoro requests to the installed package.
kokoro_owned: true
kokoro_package_home: "$PACKAGE_DISPLAY"
---

# Kokoro Router

Kokoro package root: \`$PACKAGE_DISPLAY\`

Before responding:

1. Read \`$PACKAGE_DISPLAY/IDENTITY_kokoro.md\`.
2. Route command requests to \`$PACKAGE_DISPLAY/commands/kokoro*.md\`.
3. Resolve knowledge under \`$PACKAGE_DISPLAY/knowledge/\`,
   \`$PACKAGE_DISPLAY/knowledge/google-ads/\`, and
   \`$PACKAGE_DISPLAY/knowledge/lux/\`.
4. If any required file is missing, stop and ask the user to run
   \`$PACKAGE_DISPLAY/install/verify.sh\` or reinstall Kokoro.

Never assume the current working directory is the Kokoro package.
EOF
}

initialize_meta_ads_credentials() {
    local template="$PACKAGE_HOME/connectors/meta-ads/config/meta-ads.env.template"

    require_file "$template"
    if [ -L "$META_ADS_ENV_FILE" ]; then
        echo "Kokoro setup error: credential file must not be a symlink: $META_ADS_ENV_FILE" >&2
        exit 2
    fi
    if [ -e "$META_ADS_ENV_FILE" ]; then
        if [ ! -f "$META_ADS_ENV_FILE" ]; then
            echo "Kokoro setup error: credential path is not a file: $META_ADS_ENV_FILE" >&2
            exit 2
        fi
        return
    fi

    mkdir -p "$(dirname "$META_ADS_ENV_FILE")"
    (
        umask 077
        cp "$template" "$META_ADS_ENV_FILE"
    )
    chmod 600 "$META_ADS_ENV_FILE"
}

require_file "$SOURCE_ROOT/IDENTITY_kokoro.md"
require_file "$SOURCE_MANIFEST"
require_file "$SOURCE_COMMANDS_DIR/kokoro.md"

mkdir -p "$PACKAGE_HOME" "$COMMANDS_TARGET"

if ! kokoro_same_path "$SOURCE_ROOT" "$PACKAGE_HOME"; then
    cp "$SOURCE_ROOT/IDENTITY_kokoro.md" "$PACKAGE_HOME/IDENTITY_kokoro.md"
    cp "$SOURCE_ROOT/AGENTS.md" "$PACKAGE_HOME/AGENTS.md"
    cp "$SOURCE_ROOT/.claude/CLAUDE.md" "$PACKAGE_HOME/CLAUDE.md"
    cp "$SOURCE_MANIFEST" "$PACKAGE_HOME/package.yaml"
    kokoro_copy_dir "$SOURCE_COMMANDS_DIR" "$PACKAGE_HOME/commands"
    kokoro_copy_dir "$SOURCE_KNOWLEDGE_DIR" "$PACKAGE_HOME/knowledge"
    kokoro_copy_dir "$SOURCE_ROOT/runtime" "$PACKAGE_HOME/runtime"
    kokoro_copy_dir "$SOURCE_ROOT/connectors" "$PACKAGE_HOME/connectors"

    if ! kokoro_same_path "$SCRIPT_DIR" "$PACKAGE_HOME/install"; then
        kokoro_copy_dir "$SCRIPT_DIR" "$PACKAGE_HOME/install"
    fi

    if [ -d "$SOURCE_ROOT/.agents/skills/kokoro" ]; then
        mkdir -p "$PACKAGE_HOME/.agents/skills"
        kokoro_copy_dir "$SOURCE_ROOT/.agents/skills/kokoro" "$PACKAGE_HOME/.agents/skills/kokoro"
    fi
fi

chmod +x "$PACKAGE_HOME/runtime/kokoro.py"
chmod +x "$PACKAGE_HOME/connectors/meta-ads/run.sh"
chmod +x "$PACKAGE_HOME/connectors/meta-ads/doctor.sh"

initialize_meta_ads_credentials

remove_existing_wrappers

find "$PACKAGE_HOME/commands" -maxdepth 1 -type f -name 'kokoro*.md' | sort |
while IFS= read -r source_file; do
    write_wrapper "$source_file"
done

write_codex_skill

"$PACKAGE_HOME/install/verify.sh"

echo "Kokoro installed."
echo "Package root: $PACKAGE_DISPLAY"
echo "Claude commands: $(kokoro_display_path "$COMMANDS_TARGET")"
echo "Codex skill: $(kokoro_display_path "$CODEX_SKILL_DIR")"
echo "Meta Ads connector: $PACKAGE_DISPLAY/connectors/meta-ads/run.sh"
echo "Meta Ads credentials: $(kokoro_display_path "$META_ADS_ENV_FILE")"
echo "Verify: $PACKAGE_DISPLAY/install/verify.sh"
